version: '3.8'

services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network

  chat-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - VLLM_URL=http://vllm:8000/v1/chat/completions
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - vllm
      - qdrant
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data: