services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    ports:
      - "8000:8000"
    restart: always

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    restart: always

  chat-app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - vllm
      - qdrant
    restart: always
