name: VLLM Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 vllm==0.7.0 requests pytest --index-url https://download.pytorch.org/whl/cu121
    
    - name: Run tests
      run: |
        pytest tests/test_vllm_cuda.py -v 